wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1637164131
    t:
      1:
      - 1
      2:
      - 1
      - 5
      3:
      - 1
      - 2
      - 13
      - 19
      4: 3.9.6
      5: 0.12.2
      8:
      - 1
      - 5
activation:
  desc: null
  value: gelu
adafactor_eps:
  desc: null
  value:
  - 1.0e-30
  - 0.001
adam_eps:
  desc: null
  value: 1.0e-08
add_p1_after_newln:
  desc: null
  value: false
aggregate_micro:
  desc: null
  value: false
allow_missing_init_opts:
  desc: null
  value: false
attention_dropout:
  desc: null
  value: 0.0
batchsize:
  desc: null
  value: 16
beam_block_full_context:
  desc: null
  value: true
beam_block_list_filename:
  desc: null
  value: null
beam_block_ngram:
  desc: null
  value: 3
beam_context_block_ngram:
  desc: null
  value: -1
beam_delay:
  desc: null
  value: 30
beam_length_penalty:
  desc: null
  value: 0.65
beam_min_length:
  desc: null
  value: 10
beam_size:
  desc: null
  value: 10
betas:
  desc: null
  value:
  - 0.9
  - 0.999
bpe_add_prefix_space:
  desc: null
  value: null
bpe_debug:
  desc: null
  value: false
bpe_dropout:
  desc: null
  value: null
bpe_merge:
  desc: null
  value: null
bpe_vocab:
  desc: null
  value: null
compute_tokenized_bleu:
  desc: null
  value: false
datapath:
  desc: null
  value: /home/marvin/emely/emely-models/ParlAI/data
datatype:
  desc: null
  value: train
delimiter:
  desc: null
  value: '

    '
dict_class:
  desc: null
  value: parlai.core.dict:DictionaryAgent
dict_endtoken:
  desc: null
  value: __end__
dict_file:
  desc: null
  value: /home/marvin/emely/emely-models/ParlAI/data/models/blender/blender_90M/model.dict
dict_include_test:
  desc: null
  value: false
dict_include_valid:
  desc: null
  value: false
dict_initpath:
  desc: null
  value: null
dict_language:
  desc: null
  value: english
dict_lower:
  desc: null
  value: true
dict_max_ngram_size:
  desc: null
  value: -1
dict_maxexs:
  desc: null
  value: -1
dict_maxtokens:
  desc: null
  value: -1
dict_minfreq:
  desc: null
  value: 0
dict_nulltoken:
  desc: null
  value: __null__
dict_starttoken:
  desc: null
  value: __start__
dict_textfields:
  desc: null
  value: text,labels
dict_tokenizer:
  desc: null
  value: bpe
dict_unktoken:
  desc: null
  value: __unk__
display_examples:
  desc: null
  value: false
download_path:
  desc: null
  value: null
dropout:
  desc: null
  value: 0.1
dynamic_batching:
  desc: null
  value: null
embedding_projection:
  desc: null
  value: random
embedding_size:
  desc: null
  value: 512
embedding_type:
  desc: null
  value: random
embeddings_scale:
  desc: null
  value: true
eval_batchsize:
  desc: null
  value: null
eval_dynamic_batching:
  desc: null
  value: null
evaltask:
  desc: null
  value: internal,external
ffn_size:
  desc: null
  value: 2048
force_fp16_tokens:
  desc: null
  value: false
fp16:
  desc: null
  value: true
fp16_impl:
  desc: null
  value: safe
gpu:
  desc: null
  value: -1
gradient_clip:
  desc: null
  value: 0.1
hide_labels:
  desc: null
  value: false
history_add_global_end_token:
  desc: null
  value: null
history_reversed:
  desc: null
  value: false
history_size:
  desc: null
  value: -1
image_cropsize:
  desc: null
  value: 224
image_mode:
  desc: null
  value: raw
image_size:
  desc: null
  value: 256
inference:
  desc: null
  value: beam
init_model:
  desc: null
  value: /home/marvin/emely/emely-models/ParlAI/data/models/blender/blender_90M/model
init_opt:
  desc: null
  value: null
interactive_mode:
  desc: null
  value: false
invsqrt_lr_decay_gamma:
  desc: null
  value: -1
is_debug:
  desc: null
  value: false
label_truncate:
  desc: null
  value: 128
learn_positional_embeddings:
  desc: null
  value: true
learningrate:
  desc: null
  value: 1.0e-06
load_from_checkpoint:
  desc: null
  value: true
log_every_n_secs:
  desc: null
  value: -1
log_every_n_steps:
  desc: null
  value: 50
loglevel:
  desc: null
  value: info
lr_scheduler:
  desc: null
  value: reduceonplateau
lr_scheduler_decay:
  desc: null
  value: 0.5
lr_scheduler_patience:
  desc: null
  value: 3
max_train_steps:
  desc: null
  value: -1
max_train_time:
  desc: null
  value: -1
metrics:
  desc: null
  value: ppl,bleu-4,rouge-L
model:
  desc: null
  value: transformer/generator
model_file:
  desc: null
  value: /home/marvin/emely/emely-models/models/emely-runs/jani_peralez/model
model_parallel:
  desc: null
  value: false
momentum:
  desc: null
  value: 0
multitask_weights:
  desc: null
  value:
  - 3.0
  - 2.0
  - 2.0
mutators:
  desc: null
  value: null
n_decoder_layers:
  desc: null
  value: -1
n_encoder_layers:
  desc: null
  value: -1
n_heads:
  desc: null
  value: 16
n_layers:
  desc: null
  value: 8
n_positions:
  desc: null
  value: 512
n_segments:
  desc: null
  value: 0
nesterov:
  desc: null
  value: true
no_cuda:
  desc: null
  value: false
num_epochs:
  desc: null
  value: 20.0
num_workers:
  desc: null
  value: 0
nus:
  desc: null
  value:
  - 0.7
optimizer:
  desc: null
  value: adamax
output_scaling:
  desc: null
  value: 1.0
parlai_home:
  desc: null
  value: /home/marvin/emely/emely-models/ParlAI
person_tokens:
  desc: null
  value: false
rank_candidates:
  desc: null
  value: false
relu_dropout:
  desc: null
  value: 0.0
save_after_valid:
  desc: null
  value: true
save_every_n_secs:
  desc: null
  value: 60.0
share_word_embeddings:
  desc: null
  value: true
short_final_eval:
  desc: null
  value: false
skip_generation:
  desc: null
  value: false
special_tok_lst:
  desc: null
  value: null
split_lines:
  desc: null
  value: false
starttime:
  desc: null
  value: Nov17_16-48
task:
  desc: null
  value: internal,external,external-gpt3
temperature:
  desc: null
  value: 1.0
tensorboard_log:
  desc: null
  value: true
tensorboard_logdir:
  desc: null
  value: null
text_truncate:
  desc: null
  value: 512
topk:
  desc: null
  value: 10
topp:
  desc: null
  value: 0.9
truncate:
  desc: null
  value: -1
update_freq:
  desc: null
  value: 1
use_reply:
  desc: null
  value: label
validation_cutoff:
  desc: null
  value: 1.0
validation_every_n_epochs:
  desc: null
  value: 0.25
validation_every_n_secs:
  desc: null
  value: -1
validation_every_n_steps:
  desc: null
  value: -1
validation_max_exs:
  desc: null
  value: 20000
validation_metric:
  desc: null
  value: ppl
validation_metric_mode:
  desc: null
  value: min
validation_patience:
  desc: null
  value: 15
validation_share_agent:
  desc: null
  value: false
variant:
  desc: null
  value: xlm
verbose:
  desc: null
  value: false
wandb_entity:
  desc: null
  value: null
wandb_log:
  desc: null
  value: true
wandb_name:
  desc: null
  value: jani_peralez
wandb_project:
  desc: null
  value: emely-v05_01
warmup_rate:
  desc: null
  value: 0.0001
warmup_updates:
  desc: null
  value: -1
weight_decay:
  desc: null
  value: null
